server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: file:///Users/yunukkim/Desktop/workplace/git-local-repo
